In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("Placement.csv")

In [3]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    object
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [5]:
dataset.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [6]:
dir(dataset)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'degree_p',
 'degree_t',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'etest_p',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'gender',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'hsc_b',
 'hsc_p',
 'hsc_s',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mba_p',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'salary',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sl_no',
 'sort_index',
 'sort_values',
 'specialisation',
 'squeeze',
 'ssc_b',
 'ssc_p',
 'stack',
 'status',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'workex',
 'xs']

In [7]:
from Univariate import Univariate

qual,quan=Univariate.qualQuan(dataset)

In [8]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [9]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

# CENTRAL TENDENCY -- MEAN, MEDIAN, MODE # PERCENTILE

dataset.describe() #this print the below calculated values to the quantity(number) columns

In [10]:
descriptive = Univariate.dataFrameTable(dataset,quan)

In [11]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Min,1.0,40.89,37.0,50.0,50.0,51.21,200000.0
Q1-25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2-50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3-75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99th,212.86,87.0,91.86,83.86,97.0,76.1142,NaN
Q4-100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
min,1.0,40.89,37.0,50.0,50.0,51.21,200000.0
max,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0

# INTER QUANTILE RANGE # FINDING OUTLIER

In [12]:
lesser,greater=Univariate.findOutliers(descriptive,quan)

In [13]:
lesser

['hsc_p']

In [14]:
greater

['hsc_p', 'degree_p', 'salary']

In [15]:
dataset = Univariate.replaceOutliers(dataset,descriptive,lesser,greater)

In [16]:
descriptive = Univariate.dataFrameTable(dataset,quan)

In [17]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Min,1.0,40.89,42.75,50.0,50.0,51.21,200000.0
Q1-25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2-50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3-75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99th,212.86,87.0,91.129,83.86,97.0,76.1142,NaN
Q4-100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
min,1.0,40.89,42.75,50.0,50.0,51.21,200000.0
max,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0

In [18]:
lesser,greater=Univariate.findOutliers(descriptive,quan)

In [19]:
lesser

[]

In [20]:
greater

[]

# FREQUENCY

In [21]:
all_freq_tables = {} # Dictionary to store results

for columnName in quan:
    all_freq_tables[columnName]=Univariate.freqTable(columnName,dataset)

In [22]:
# Example: Access the frequency table for 'ssc_p'
all_freq_tables['ssc_p']

     Unique_Values  Frequency  Relative_Frequency    Cumsum
0            62.00         11            0.106796  0.106796
1            63.00         10            0.097087  0.203883
2            67.00          9            0.087379  0.291262
3            73.00          9            0.087379  0.378641
4            52.00          9            0.087379  0.466019
..             ...        ...                 ...       ...
98           55.68          1            0.009709  2.048544
99           41.00          1            0.009709  2.058252
100          83.33          1            0.009709  2.067961
101          43.00          1            0.009709  2.077670
102          80.60          1            0.009709  2.087379

[103 rows x 4 columns]

In [23]:
#Print all quantity frequency table details
for col_name, table in all_freq_tables.items():
    print(f"Frequency table for: {col_name}")
    print(table)
    print("-" * 40)

Frequency table for: sl_no
     Unique_Values  Frequency  Relative_Frequency    Cumsum
0                1          1            0.004651  0.004651
1                2          1            0.004651  0.009302
2                3          1            0.004651  0.013953
3                4          1            0.004651  0.018605
4                5          1            0.004651  0.023256
..             ...        ...                 ...       ...
210            211          1            0.004651  0.981395
211            212          1            0.004651  0.986047
212            213          1            0.004651  0.990698
213            214          1            0.004651  0.995349
214            215          1            0.004651  1.000000

[215 rows x 4 columns]
----------------------------------------
Frequency table for: ssc_p
     Unique_Values  Frequency  Relative_Frequency    Cumsum
0            62.00         11            0.106796  0.106796
1            63.00         10            0.097087  0.203883
2            67.00          9            0.087379  0.291262
3            73.00          9            0.087379  0.378641
4            52.00          9            0.087379  0.466019
..             ...        ...                 ...       ...
98           55.68          1            0.009709  2.048544
99           41.00          1            0.009709  2.058252
100          83.33          1            0.009709  2.067961
101          43.00          1            0.009709  2.077670
102          80.60          1            0.009709  2.087379

[103 rows x 4 columns]
----------------------------------------
Frequency table for: hsc_p
    Unique_Values  Frequency  Relative_Frequency    Cumsum
0           63.00         14            0.153846  0.153846
1           62.00         12            0.131868  0.285714
2           67.00          9            0.098901  0.384615
3           60.00          9            0.098901  0.483516
4           70.00          8            0.087912  0.571429
..            ...        ...                 ...       ...
86          65.50          1            0.010989  2.318681
87          77.60          1            0.010989  2.329670
88          70.20          1            0.010989  2.340659
89          61.40          1            0.010989  2.351648
90          61.33          1            0.010989  2.362637

[91 rows x 4 columns]
----------------------------------------
Frequency table for: degree_p
    Unique_Values  Frequency  Relative_Frequency    Cumsum
0           65.00         20            0.224719  0.224719
1           66.00         13            0.146067  0.370787
2           72.00         12            0.134831  0.505618
3           64.00         11            0.123596  0.629213
4           58.00          9            0.101124  0.730337
..            ...        ...                 ...       ...
84          64.80          1            0.011236  2.370787
85          56.30          1            0.011236  2.382022
86          88.50          1            0.011236  2.393258
87          56.87          1            0.011236  2.404494
88          77.60          1            0.011236  2.415730

[89 rows x 4 columns]
----------------------------------------
Frequency table for: etest_p
    Unique_Values  Frequency  Relative_Frequency  Cumsum
0           60.00         14                0.14    0.14
1           80.00          8                0.08    0.22
2           67.00          7                0.07    0.29
3           75.00          7                0.07    0.36
4           89.00          6                0.06    0.42
..            ...        ...                 ...     ...
95          87.55          1                0.01    2.11
96          61.28          1                0.01    2.12
97          88.56          1                0.01    2.13
98          92.66          1                0.01    2.14
99          91.00          1                0.01    2.15

[100 rows x 4 columns]
----------------------------------------
Frequency table for: mba_p
     Unique_Values  Frequency  Relative_Frequency    Cumsum
0            56.70          3            0.014634  0.014634
1            62.48          2            0.009756  0.024390
2            64.15          2            0.009756  0.034146
3            64.08          2            0.009756  0.043902
4            61.29          2            0.009756  0.053659
..             ...        ...                 ...       ...
200          74.49          1            0.004878  1.029268
201          53.62          1            0.004878  1.034146
202          69.72          1            0.004878  1.039024
203          60.23          1            0.004878  1.043902
204          60.22          1            0.004878  1.048780

[205 rows x 4 columns]
----------------------------------------
Frequency table for: salary
    Unique_Values  Frequency  Relative_Frequency    Cumsum
0        300000.0         22            0.611111  0.611111
1        250000.0         18            0.500000  1.111111
2        240000.0         15            0.416667  1.527778
3        390000.0         15            0.416667  1.944444
4        260000.0          7            0.194444  2.138889
5        200000.0          6            0.166667  2.305556
6        360000.0          6            0.166667  2.472222
7        265000.0          6            0.166667  2.638889
8        275000.0          5            0.138889  2.777778
9        220000.0          5            0.138889  2.916667
10       270000.0          4            0.111111  3.027778
11       210000.0          4            0.111111  3.138889
12       350000.0          3            0.083333  3.222222
13       216000.0          3            0.083333  3.305556
14       204000.0          2            0.055556  3.361111
15       236000.0          2            0.055556  3.416667
16       230000.0          2            0.055556  3.472222
17       280000.0          2            0.055556  3.527778
18       218000.0          2            0.055556  3.583333
19       252000.0          2            0.055556  3.638889
20       276000.0          2            0.055556  3.694444
21       320000.0          1            0.027778  3.722222
22       278000.0          1            0.027778  3.750000
23       231000.0          1            0.027778  3.777778
24       287000.0          1            0.027778  3.805556
25       268000.0          1            0.027778  3.833333
26       336000.0          1            0.027778  3.861111
27       380000.0          1            0.027778  3.888889
28       225000.0          1            0.027778  3.916667
29       233000.0          1            0.027778  3.944444
30       340000.0          1            0.027778  3.972222
31       255000.0          1            0.027778  4.000000
32       285000.0          1            0.027778  4.027778
33       290000.0          1            0.027778  4.055556
34       264000.0          1            0.027778  4.083333
35       295000.0          1            0.027778  4.111111
----------------------------------------